### ISSUE TITLE
Seems to be down?

### ISSUE THREAD

**Issue by Arefu** [hagata/ranmoji#2]
I am getting application error whenever I try a GET request on the page. Is it down?

**Comment by hagata** [comment]
Yup it’s down right now. I turned off the heroku app

**Comment by Arefu** [comment]
Awh, any reason? Any plans to bring it back up?

**Comment by hagata** [comment]
It's on a free Heroku Dyno and was running up its hours. 
It's back up for now & dyno hours reset each month. 👍

**Comment by Arefu** [comment]
Ah, fair enough! Thanks!
